[project]
name = 'granite-core'
description = 'Granite v1 core smart contracts'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.state-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.math-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.constants-v1'

[[project.requirements]]
contract_id = 'SP3BJR4P3W2Y9G22HA595Z59VHBC9EQYRFWSKG743.constants-v2'

[[project.requirements]]
contract_id = 'SP3Y2ZSH8P7D50B0VBTSX11S7XSG24M1VB9YFQA4K.token-aeusdc'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-registry'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.linear-kinked-ir-v1'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-oracle-v4'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-storage-v4'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-pnau-decoder-v3'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.wormhole-core-v4'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.meta-governance-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.staking-reward-v1'

[[project.requirements]]
contract_id = 'SP3BJR4P3W2Y9G22HA595Z59VHBC9EQYRFWSKG743.staking-v1'

[contracts.borrower-v1]
path = 'contracts/borrower-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.flash-loan-v1]
path = 'contracts/flash-loan-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.governance-v1]
path = 'contracts/governance-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.liquidator-v1]
path = 'contracts/liquidator-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.liquidity-provider-v1]
path = 'contracts/liquidity-provider-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.pyth-adapter-v1]
path = 'contracts/modules/pyth-adapter-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.trait-flash-loan-v1]
path = 'contracts/traits/trait-flash-loan-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.withdrawal-caps-util-v1]
path = 'contracts/modules/withdrawal-caps-util-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.withdrawal-caps-v1]
path = 'contracts/modules/withdrawal-caps-v1.clar'
clarity_version = 3
epoch = '3.0'
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
