[project]
name = 'granite-core'
description = 'Granite v1 core smart contracts'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-cursor-v2'

[[project.requirements]]
contract_id = 'SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-ecc-v1'

[[project.requirements]]
contract_id = 'SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-merkle-tree-keccak160-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.state-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.linear-kinked-ir-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.pyth-adapter-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.meta-governance-v1'

[[project.requirements]]
contract_id = 'SP35E2BBMDT2Y1HB0NTK139YBGYV3PAPK3WA8BRNA.staking-reward-v1'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP3Y2ZSH8P7D50B0VBTSX11S7XSG24M1VB9YFQA4K.token-aeusdc'

[contracts.borrower-v1]
path = 'contracts/borrower-v1.clar'
clarity_version = 3
epoch = 3.0

[contracts.constants-v2]
path = 'contracts/constants-v2.clar'
clarity_version = 3
epoch = 3.0

[contracts.flash-loan-v1]
path = 'contracts/flash-loan-v1.clar'
clarity_version = 3
epoch = 3.0

[contracts.governance-v1]
path = 'contracts/governance-v1.clar'
clarity_version = 3
epoch = 3.0

[contracts.liquidator-v1]
path = 'contracts/liquidator-v1.clar'
clarity_version = 3
epoch = 3.0

[contracts.liquidity-provider-v1]
path = 'contracts/liquidity-provider-v1.clar'
clarity_version = 3
epoch = 3.0

[contracts.staking-v1]
path = 'contracts/staking-v1.clar'
clarity_version = 3
epoch = 3.0

[contracts.trait-flash-loan-v1]
path = 'contracts/traits/trait-flash-loan-v1.clar'
clarity_version = 3
epoch = 3.0

[contracts.utility]
path = 'contracts/modules/utility.clar'
clarity_version = 3
epoch = 3.0

[contracts.withdrawal-caps-v1]
path = 'contracts/modules/withdrawal-caps-v1.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
