[project]
name = 'granite-core'
description = 'Granite v1 core smart contracts'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP120SBRBQJ00MCWS7TM5R8WJNTTKD5K0HFRC2CNE.usdcx'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-storage-v4'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-oracle-v4'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-pnau-decoder-v3'

[[project.requirements]]
contract_id = 'SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.wormhole-core-v4'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

[contracts.borrower-v1]
path = 'contracts/borrower-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.constants-v1]
path = 'contracts/constants-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.constants-v2]
path = 'contracts/constants-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.flash-loan-v1]
path = 'contracts/flash-loan-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.governance-v1]
path = 'contracts/governance-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.linear-kinked-ir-v1]
path = 'contracts/modules/linear-kinked-ir-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.linear-linked-ir-utility]
path = 'contracts/modules/linear-kinked-ir-utility.clar'
clarity_version = 3
epoch = '3.0'

[contracts.liquidator-v1]
path = 'contracts/liquidator-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.liquidity-provider-v1]
path = 'contracts/liquidity-provider-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.lp-incentives-v2]
path = 'contracts/lp-incentives-v2.clar'
clarity_version = 3
epoch = '3.0'

[contracts.math-v1]
path = 'contracts/modules/math-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.meta-governance-v1]
path = 'contracts/meta-governance-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.pyth-adapter-v1]
path = 'contracts/modules/pyth-adapter-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.staking-reward-v1]
path = 'contracts/modules/staking-reward-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.staking-v1]
path = 'contracts/staking-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.state-v1]
path = 'contracts/state-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.stx-claim]
path = 'contracts/stx-claim.clar'
clarity_version = 3
epoch = '3.0'

[contracts.trait-flash-loan-v1]
path = 'contracts/traits/trait-flash-loan-v1.clar'
clarity_version = 3
epoch = '3.0'

[contracts.utility]
path = 'contracts/modules/utility.clar'
clarity_version = 3
epoch = '3.0'

[contracts.withdrawal-caps-v1]
path = 'contracts/modules/withdrawal-caps-v1.clar'
clarity_version = 3
epoch = '3.0'
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
